name: Quality Assurance

on:
  push:
  pull_request:

jobs:
  build-linux:
    runs-on: self-hosted
    strategy:
      matrix:
        os: [Linux]
        platform: [x64]
        compiler: [gcc, clang]
        configure:
          - {label: "with parser generation", opt: "--enable-parser-generation" }
          - {label: "wo curl",    opt: "--without-curl" }
          - {label: "wo yajl",    opt: "--without-yajl" }
          - {label: "wo geoip",   opt: "--without-geoip" }
          - {label: "wo lmdb",    opt: "--without-lmdb" }
          - {label: "wo ssdeep",  opt: "--without-ssdeep" }
          - {label: "wo lua",     opt: "--without-lua" }
          - {label: "without maxmind", opt: "--without-maxmind" }
    steps:
      - name: Setup Dependencies
        run: |
          sudo yum -y install yajl-devel
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: build.sh
        run: ./build.sh
      - name: configure ${{ matrix.configure.label }}
        run: ./configure ${{ matrix.configure.opt }}
      - uses: ammaraskar/gcc-problem-matcher@master
      - name: make
        run: make -j `nproc`
      - name: check
        run: make check
      - name: check-static
        run: make check-static
